### ISSUE TITLE
All values in vertices is nan

### ISSUE THREAD

**Issue by greenfield932** [grepthat/libOpenDRIVE#33]
Hi, I can't get valid lane coordinates, just added output in test.cpp of lane points, my output is all nan
`
for(auto p: lane_pts)
{
         printf("%.2f %.2f %.2f\n", p[0], p[1], p[2]);
}
`

./test-xodr ../Viewer/data.xodr 

road: 500, length: 16.52
road: 501, length: 4.00
road: 502, length: 4.00
road: 503, length: 16.52
road: 504, length: 20.00
road: 505, length: 20.00
road: 506, length: 20.00
road: 507, length: 20.00
road: 508, length: 541.50
road: 509, length: 541.50
road: 510, length: 16.12
road: 511, length: 16.12
road: 512, length: 16.12
road: 513, length: 16.12
road: 514, length: 4.00
road: 515, length: 16.52
road: 516, length: 4.00
road: 517, length: 16.52
Finished, got 320 lane points, 256 roadmark points
-nan -nan -nan
-nan -nan -nan
-nan -nan -nan
-nan -nan -nan
-nan -nan -nan
-nan -nan -nan
-nan -nan -nan
-nan -nan -nan
-nan -nan -nan

**Comment by ilyas-gazizov** [comment]
The issue is in  odr_map.get_roads() function which calls get_map_values and correspondingly calls RefLine copy ctor.

`RefLine::RefLine(const RefLine& other) : road_id(other.road_id), length(other.length), elevation_profile(other.elevation_profile)
{
    for (const auto& s0_geometry : this->s0_to_geometry)
        this->s0_to_geometry.insert({s0_geometry.first, s0_geometry.second->clone()});
}`

There is a mistake using this ptr instead of const RefLine& other.
